name = "decepticon"
version = "1.0.1"

description = "StateT/Result in Gleam"
licences = ["ISC"]
repository = { type = "github", user = "abradley2", repo = "decepticon" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
