name = "decepticon"
version = "1.0.0"

description = "A Gleam library"
licences = ["ISC"]
repository = { type = "github", user = "abradley2", repo = "decepticon" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
